<?php

class CERTICATE_CATEGORY
{
    static $ALL_REGISTERED_USERS = "ALL_REGISTERED_USERS";
    static $ALL_PARTICIPATED_USERS = "ALL_PARTICIPATED_USERS";
    static $SEND_BY_USER_EMAIL = "SEND_BY_USER_EMAIL";
}
